version: '3.1'

services: 
  persona_api:
    container_name: persona_api
    restart: always 
    build: .
    ports: 
      - "3000:3000"
    links: 
      - mongo
  
  mongo: 
    container_name: mongo
    image: mongo
    restart: always
    volumes: 
      - ../.personadata:/data/db
    ports: 
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
