version: '3.1'

services:
  persona_api:
    container_name: persona_api
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - "constraint:ostype==x64"

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      - "constraint:ostype==x64"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - "constraint:ostype==x64"

