version: '2'

services: 
  persona_api:
    container_name: persona_api
    restart: always 
    build: .
    ports: 
      - "3000:3000"
    links: 
      - mongo_persona
  
  mongo_persona: 
    container_name: mongo_persona
    image: mongo
    volumes: 
      - ./data:/data/db
    ports: 
      - "27017:27017"
